namespace SpriteKind {
    export const skeleife = SpriteKind.create()
    export const player2 = SpriteKind.create()
    export const flame = SpriteKind.create()
    export const blast = SpriteKind.create()
}
namespace StatusBarKind {
    export const player2health = StatusBarKind.create()
}
sprites.onOverlap(SpriteKind.Player, SpriteKind.flame, function (sprite, otherSprite) {
    player_1_health.value += -30
    sprites.destroy(otherSprite)
})
controller.player1.onButtonEvent(ControllerButton.Up, ControllerButtonEvent.Pressed, function () {
    if (game.runtime() - jump1 >= jump_cooldown1) {
        jump1 = game.runtime()
        Player_1.vy = -100
    }
})
function menu () {
    if (mainmenu == 1) {
        scene.setBackgroundColor(2)
        game.showLongText("press A to play", DialogLayout.Bottom)
        mainmenu += -1
    }
    if (mainmenu == 0) {
        scene.setBackgroundColor(15)
        jump1 = 0
        jump_cooldown1 = 1300
        jump = 0
        jump_cooldown = 1300
        knife_throw = 0
        knife_2 = 0
        knife_2_cool = 1300
        knife_throw_cooldown = 1300
        Player_1 = sprites.create(img`
            . . . . . f f f f f f . . . . . 
            . . . f f e e e e f 2 f . . . . 
            . . f f e e e e f 2 2 2 f . . . 
            . . f e e e f f e e e e f . . . 
            . . f f f f e e 2 2 2 2 e f . . 
            . . f e 2 2 2 f f f f e 2 f . . 
            . f f f f f f f e e e f f f . . 
            . f f e 4 4 e b f 4 4 e e f . . 
            . f e e 4 d 4 1 f d d e f f . . 
            . . f e e e 4 d d d d f d d f . 
            . . . f f e e 4 e e e f b b f . 
            . . . . f 2 2 2 4 d d e b b f . 
            . . . . e 2 2 2 e d d e b f . . 
            . . . . f 4 4 4 f e e f f . . . 
            . . . . . f f f f f f . . . . . 
            . . . . . . f f f . . . . . . . 
            `, SpriteKind.Player)
        player_1_health = statusbars.create(20, 4, StatusBarKind.Health)
        player_1_health.attachToSprite(Player_1)
        Player_1.setPosition(6, 104)
        tiles.setCurrentTilemap(tilemap`level1`)
        controller.player1.moveSprite(Player_1, 100, 0)
        Player_2 = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            .........fffff..........
            ........f11111ff........
            .......fb111111bf.......
            .......f1111111dbf......
            ......fd111111dddf......
            ......fd11111ddddf......
            ......fd11dddddddf......
            ......f111dddddddf......
            ......f11fcddddddf......
            .....fb1111bdddbf.......
            .....f1b1bdfcfff........
            .....fbfbffffffff.......
            ......fffffffffff.ff....
            ...........ffffffff.....
            ........f1b1bffffff.....
            ........fbfbffffff......
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.player2)
        Player_2.setPosition(149, 108)
        controller.player2.moveSprite(Player_2, 100, 0)
        player_2_health = statusbars.create(20, 4, StatusBarKind.player2health)
        Player_1.ay = 150
        Player_2.ay = 150
        player_2_health.attachToSprite(Player_2)
        player_1_health.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
        player_2_health.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
        Player_1.setStayInScreen(true)
        Player_2.setStayInScreen(true)
    }
}
controller.player2.onButtonEvent(ControllerButton.A, ControllerButtonEvent.Pressed, function () {
    if (game.runtime() - knife_2 >= knife_2_cool) {
        projectile = sprites.createProjectileFromSprite(img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            .............c..........
            .......ccccccccccc......
            ........dddddccccc......
            .........ccccccccc......
            .............c..........
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `, Player_2, -100, 0)
        knife_2 = game.runtime()
        projectile.setKind(SpriteKind.skeleife)
    }
})
controller.player2.onButtonEvent(ControllerButton.Up, ControllerButtonEvent.Pressed, function () {
    if (game.runtime() - jump >= jump_cooldown) {
        jump = game.runtime()
        Player_2.vy = -100
    }
})
statusbars.onZero(StatusBarKind.Health, function (status) {
    mp.gameOverPlayerWin(mp.playerSelector(mp.PlayerNumber.Two))
})
statusbars.onZero(StatusBarKind.player2health, function (status) {
    mp.gameOverPlayerWin(mp.playerSelector(mp.PlayerNumber.One))
})
controller.player1.onButtonEvent(ControllerButton.A, ControllerButtonEvent.Pressed, function () {
    if (game.runtime() - knife_throw >= knife_throw_cooldown) {
        projectile = sprites.createProjectileFromSprite(img`
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            .............c..........
            .........ccccccccccc....
            .........cccccddddd.....
            .........ccccccccc......
            .............c..........
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            ........................
            `, Player_1, 100, 0)
        knife_throw = game.runtime()
    }
})
sprites.onOverlap(SpriteKind.player2, SpriteKind.Projectile, function (sprite, otherSprite) {
    if (normalmode) {
        player_2_health.value += -10
        sprites.destroy(otherSprite)
    }
    if (hardmode) {
        player_2_health.value += -5
        sprites.destroy(otherSprite)
    }
    if (hardmode && normalmode) {
        player_2_health.value += 13
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.skeleife, function (sprite, otherSprite) {
    if (normalmode) {
        player_1_health.value += -10
        sprites.destroy(otherSprite)
    }
    if (hardmode) {
        player_1_health.value += -20
        sprites.destroy(otherSprite)
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.blast, function (sprite, otherSprite) {
    player_1_health.value += -50
    sprites.destroy(otherSprite)
})
let projectile: Sprite = null
let player_2_health: StatusBarSprite = null
let Player_2: Sprite = null
let knife_throw_cooldown = 0
let knife_2_cool = 0
let knife_2 = 0
let knife_throw = 0
let jump_cooldown = 0
let jump = 0
let Player_1: Sprite = null
let jump_cooldown1 = 0
let jump1 = 0
let player_1_health: StatusBarSprite = null
let mainmenu = 0
let hardmode = false
let normalmode = false
normalmode = true
let _1player = true
hardmode = false
mainmenu += 1
menu()
game.onUpdateInterval(1000, function () {
    if (mp.isConnected(mp.playerSelector(mp.PlayerNumber.Two))) {
        _1player = false
    }
    if (_1player) {
        if (Math.percentChance(80)) {
            if (normalmode) {
                Player_2.vx = randint(-100, 100)
                if (game.runtime() - jump >= jump_cooldown) {
                    Player_2.vy = randint(-10, -100)
                    jump = game.runtime()
                    if (game.runtime() - knife_2 >= knife_2_cool) {
                        projectile = sprites.createProjectileFromSprite(img`
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            .............c..........
                            .......ccccccccccc......
                            ........dddddccccc......
                            .........ccccccccc......
                            .............c..........
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            `, Player_2, -100, 0)
                        knife_2 = game.runtime()
                        projectile.setKind(SpriteKind.skeleife)
                    }
                }
            }
        }
        if (hardmode) {
            if (Math.percentChance(80)) {
                let flame = 0
                Player_2.vx = randint(-100, 100)
                Player_2.vy = randint(-10, -100)
                if (game.runtime() - flame >= knife_2_cool) {
                    projectile = sprites.createProjectileFromSprite(img`
                        ........................
                        ........................
                        ........................
                        ........................
                        .............4..........
                        .............4..........
                        .............4..........
                        .............4..........
                        .............4..........
                        .............4..........
                        .............4..........
                        .....4444444444444......
                        ..4444444444444444......
                        .....4444444444444......
                        .......4..4..4..4.......
                        .......4.....4..........
                        .............4..........
                        .............4..........
                        .............4..........
                        ........................
                        ........................
                        ........................
                        ........................
                        ........................
                        `, Player_2, -200, 0)
                    projectile.setKind(SpriteKind.flame)
                }
                if (hardmode && normalmode) {
                    if (Math.percentChance(20)) {
                        projectile = sprites.createProjectileFromSprite(img`
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            .......9999999..........
                            ......999999999.........
                            .....99.99999.99........
                            .....99999999999........
                            .....99999999999........
                            .....99999.99999........
                            .....99999999999........
                            .....99999999999........
                            .....99.99999.99........
                            ......999999999.........
                            .......9999999..........
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            ........................
                            `, Player_2, -200, 0)
                        projectile.setKind(SpriteKind.blast)
                    }
                }
            }
        }
    }
})
